### PR TITLE
fix deprecated BooleanParameter

### PR DESCRIPTION
**Pull request by muddydixon**
## Summary
* BooleanParameter is deprecated

### CODE REVIEW

**Comment by toru-takahashi** [comment]
Thank you for your PR.
@yyuu Could you take a look?

It looks BoolParameter was introduced in 1.0.21. BooleanParameter was deprecated in 2.0.0 and removed in 2.5.0.
https://github.com/spotify/luigi/pull/1959

Our requirement is luigi>=1.1.2,<2.5.0
So, it looks no problem.

**Review by yyuu — COMMENTED** [review]
Looks good to me :+1:

**Comment by toru-takahashi** [comment]
Thank you!

**Comment by yyuu** [comment]
Released 0.6.9 to PyPI https://pypi.python.org/pypi/luigi-td/0.6.9

**Pull request merged**
